{
 "title": "ONTAP: Changelog Monitor",
 "description": "The ONTAP Changelog Monitor, tracks configuration modifications in volumes, SVMs, and nodes, is deactivated by default. To leverage this feature, one must enable the ChangeLog plugin within the Volume, SVM, and Node Templates.",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Important Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<br>\n\nTo use this dashboard, enable the ChangeLog plugin for node, svm, and volume templates. For more details, visit the [ChangeLog documentation](https://netapp.github.io/harvest/latest/plugins/#changelog).\n"
   }
  },
  {
   "title": "Node Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create",
     "type": "stat",
     "description": "This change type indicates that a new ONTAP object has been created.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"node\",op=\"create\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "Update",
     "type": "stat",
     "description": "This change type indicates that an existing ONTAP object has been updated.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"node\",op=\"update\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "Delete",
     "type": "stat",
     "description": "This change type indicates that an existing ONTAP object has been deleted.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"node\",op=\"delete\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "Node Changes ",
     "type": "table",
     "description": "`Poller Time:` The timestamp when Harvest Poller captured the change \n\n`Object:` The name of the ONTAP object that was changed (e.g., volume, svm, node)  \n\n`OP:` The type of change that was made (e.g., create, update, delete)  \n\n`Track:` Property of the object which was modified  \n\n`New Value:` The new value of the property after the change was made  \n\n`Old Value:` The previous value of the property before the change was made \n\n*Note:* `Old Value` and `New Value` are only available for label changes and not for metric changes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "last_over_time(\n  change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"node\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "SVM Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create",
     "type": "stat",
     "description": "This change type indicates that a new ONTAP object has been created.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"svm\",op=\"create\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "Update",
     "type": "stat",
     "description": "This change type indicates that an existing ONTAP object has been updated.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"svm\",op=\"update\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "Delete",
     "type": "stat",
     "description": "This change type indicates that an existing ONTAP object has been deleted.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"svm\",op=\"delete\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "SVM Changes ",
     "type": "table",
     "description": "`Poller Time:` The timestamp when Harvest Poller captured the change \n\n`Object:` The name of the ONTAP object that was changed (e.g., volume, svm, node)  \n\n`OP:` The type of change that was made (e.g., create, update, delete)  \n\n`Track:` Property of the object which was modified  \n\n`New Value:` The new value of the property after the change was made  \n\n`Old Value:` The previous value of the property before the change was made \n\n*Note:* `Old Value` and `New Value` are only available for label changes and not for metric changes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "last_over_time(change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"svm\",netapp_cluster=~\"$NetappCluster\"}[$__range])"
      }
     ]
    }
   ]
  },
  {
   "title": "Volume Changes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Create",
     "type": "stat",
     "description": "This change type indicates that a new ONTAP object has been created.",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\",op=\"create\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "Update",
     "type": "stat",
     "description": "This change type indicates that an existing ONTAP object has been updated.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\",op=\"update\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "Delete",
     "type": "stat",
     "description": "This change type indicates that an existing ONTAP object has been deleted.",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (cluster, datacenter, object) (\n  last_over_time(\n    change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\",op=\"delete\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n  )\n)"
      }
     ]
    },
    {
     "title": "Volume Changes ",
     "type": "table",
     "description": "`Poller Time:` The timestamp when Harvest Poller captured the change \n\n`Object:` The name of the ONTAP object that was changed (e.g., volume, svm, node)  \n\n`OP:` The type of change that was made (e.g., create, update, delete)  \n\n`Track:` Property of the object which was modified  \n\n`New Value:` The new value of the property after the change was made  \n\n`Old Value:` The previous value of the property before the change was made \n\n*Note:* `Old Value` and `New Value` are only available for label changes and not for metric changes.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "last_over_time(\n  change_log{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",object=~\"volume\",netapp_cluster=~\"$NetappCluster\"}[$__range]\n)"
      }
     ]
    }
   ]
  }
 ]
}