{
 "title": "ONTAP: FPolicy",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(svm_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, svm)"
    }
   },
   {
    "name": "FPolicy",
    "query": {
     "query": "label_values(fpolicy_aborted_requests{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}, policy)  "
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about FPolicy Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "\nThis dashboard requires ZapiPerf Collector. It is not currently available via RestPerf."
   }
  },
  { "title": "Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Top $TopResources Policy by IO Processing Latency",
   "type": "timeseries",
   "description": "Average IO processing latency for screen request.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fpolicy_io_processing_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_io_processing_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{policy}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Policy by IO Thread Wait Latency",
   "type": "timeseries",
   "description": "Average IO thread wait latency for the screen request.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fpolicy_io_thread_wait_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_io_thread_wait_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{policy}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Policy by Processing Latency",
   "type": "timeseries",
   "description": "Average policy processing latency for screen request.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fpolicy_processing_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_processing_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{policy}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Policy by Aborted Requests",
   "type": "timeseries",
   "description": "Number of screen requests aborted.",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fpolicy_aborted_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_aborted_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{policy}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Policy by Denied Requests",
   "type": "timeseries",
   "description": "Number of screen requests for which deny is received from fpolicy server.",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fpolicy_denied_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_denied_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{policy}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Policy by Processed Requests",
   "type": "timeseries",
   "description": "Number of screen requests went through fpolicy processing.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fpolicy_processed_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_processed_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",policy=~\"$FPolicy\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{policy}}"
    }
   ]
  },
  {
   "title": "SVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources SVM by IO Processing Latency",
     "type": "timeseries",
     "description": "Average IO processing latency for screen request.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "fpolicy_svm_io_processing_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_svm_io_processing_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}}"
      }
     ]
    },
    {
     "title": "Top $TopResources SVM by IO Thread Wait Latency",
     "type": "timeseries",
     "description": "Average IO thread wait latency for screen request.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "fpolicy_svm_io_thread_wait_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_svm_io_thread_wait_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}}"
      }
     ]
    },
    {
     "title": "Top $TopResources SVM by Aborted Requests",
     "type": "timeseries",
     "description": "Number of screen requests aborted.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fpolicy_svm_aborted_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_svm_aborted_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}}"
      }
     ]
    },
    {
     "title": "Top $TopResources SVM by Cifs Requests",
     "type": "timeseries",
     "description": "Number of cifs screen requests sent to fpolicy server.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fpolicy_svm_cifs_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_svm_cifs_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}}"
      }
     ]
    },
    {
     "title": "Top $TopResources SVM by Failed File Operation",
     "type": "timeseries",
     "description": "Number of failed file operation notifications sent to fpolicy server.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fpolicy_svm_failedop_notifications{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_svm_failedop_notifications{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Servers by Max Request Latency",
     "type": "timeseries",
     "description": "Maximum latency for a screen request.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "fpolicy_server_max_request_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_server_max_request_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}} - {{server}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Servers by Request Latency",
     "type": "timeseries",
     "description": "Average latency for screen request.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "fpolicy_server_request_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_server_request_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}} - {{server}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Servers by Cancelled Requests",
     "type": "timeseries",
     "description": "Number of screen requests whose processing was cancelled (cancel timeout).",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fpolicy_server_cancelled_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_server_cancelled_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}} - {{server}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Servers by Failed Requests",
     "type": "timeseries",
     "description": "Number of screen requests the node failed to send to fpolicy server.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fpolicy_server_failed_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_server_failed_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}} - {{server}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Servers by Outstanding Requests",
     "type": "timeseries",
     "description": "Total number of screen requests waiting for response.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fpolicy_server_outstanding_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_server_outstanding_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}} - {{server}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Servers by Processed Requests",
     "type": "timeseries",
     "description": "Total number of screen requests processed(sync and async).",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "fpolicy_server_processed_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      fpolicy_server_processed_requests{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{svm}} - {{server}}"
      }
     ]
    }
   ]
  }
 ]
}