{
 "title": "ONTAP: Headroom",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   { "name": "Interval", "query": "hourly, daily, weekly, monthly" },
   {
    "name": "OptimalPointAggr",
    "query": {
     "query": "query_result(headroom_aggr_optimal_point_confidence_factor{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"} > 1)"
    }
   },
   {
    "name": "OptimalPointCPU",
    "query": {
     "query": "query_result(headroom_cpu_optimal_point_confidence_factor{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"} > 1)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Available Ops", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Available Ops: Aggregate",
   "type": "timeseries",
   "description": "A projection of the amount of available IOP/s each aggregate has with the current workloads before increased hockey stick style latencies are encountered.<br/><br/>This graph displays the difference between Aggregate Utilization and Peak Performance (Optimal Point) as Available Ops (aka Headroom). If the current Available utilization is very low or negative for an extended time, a performance remediation plan might be appropriate. A performance remediation plan might include setting QoS workload limits, moving volumes or LUNs to another storage controller, or expanding the storage cluster.<br/><br/>This graph displays aggregate with confidence factor greater than 1. The confidence factor is used to gauge the accuracy of the optimal point for the given resource. Denoted by the following values:<br/>\n1 - Low - Seed value is used for optimal point. There's not enough data to predict optimal point.<br/>\n2 - Medium - Some data to extrapolate optimal point.<br/>\n3 - High - Substantial data which reaches or exceeds optimal point, thereby the \"optimal point\" is known. <br/>\n0 - Unknown - The resource is not available or is not in use, or there's an internal error such that the data cannot be retrieved. <br/>\nFor more details see \nhttps://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Is_my_controller_overloaded%3F",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "headroom_aggr_optimal_point_ops{aggr=~\"$OptimalPointAggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n-\n  headroom_aggr_current_ops{aggr=~\"$OptimalPointAggr\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Available Ops: CPU",
   "type": "timeseries",
   "description": "A projection of the amount of available IOP/s each node has with the current workloads before increased hockey stick style latencies are encountered.<br/><br/>This graph displays the difference between CPU Utilization and Peak Performance (Optimal Point) as Available Ops (aka Headroom). If the current Available utilization is very low or negative for an extended time, a performance remediation plan might be appropriate. A performance remediation plan might include setting QoS workload limits, moving volumes or LUNs to another storage controller, or expanding the storage cluster.<br/><br/>This graph displays node with confidence factor greater than 1. The confidence factor is used to guage the accuracy of the optimal point for the given resource.Denoted by the following values:<br/>\n1 - Low - Seed value is used for optimal point. There's not enough data to predict optimal point.<br/>\n2 - Medium - Some data to extrapolate optimal point.<br/>\n3 - High - Substantial data which reaches or exceeds optimal point, thereby the \"optimal point\" is known. <br/>\n0 - Unknown - The resource is not available or is not in use, or there's an internal error such that the data cannot be retrieved. <br/>\nFor more details see\nhttps://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Is_my_controller_overloaded%3F",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "headroom_cpu_optimal_point_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$OptimalPointCPU\",netapp_cluster=~\"$NetappCluster\"}\n-\n  headroom_cpu_current_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$OptimalPointCPU\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Aggregate Headroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_aggr_current_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Current IOP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "headroom_aggr_current_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Current Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_aggr_current_utilization{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_aggr_optimal_point_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Optimal-Point IOP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_aggr_optimal_point_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_aggr_optimal_point_utilization{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"latency\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval IOP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"ops\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"utilization\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"optimal_point_latency\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point IOP/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"optimal_point_ops\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_aggr_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"optimal_point_utilization\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Headroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Current CPU Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Current Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_current_utilization{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_optimal_point_utilization{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"latency\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"ops\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"utilization\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}} - {{aggr}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"optimal_point_latency\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"optimal_point_ops\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "EWMA $Interval Optimal-Point Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "headroom_cpu_ewma_${Interval,netapp_cluster=~\"$NetappCluster\"}{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"optimal_point_utilization\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}