{
 "title": "ONTAP: LUN",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(lun_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(lun_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}, volume)"
    }
   },
   {
    "name": "LUN",
    "query": {
     "query": "label_values(lun_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\", volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"},lun)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Luns by Average Read Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  topk(\n    $TopResources,\n    lun_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Luns by Average Write Latency",
   "type": "stat",
   "description": "Average Latency of top $TopResources volumes.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(\n  topk(\n    $TopResources,\n    lun_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Luns by Read Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  topk(\n    $TopResources,\n    lun_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Luns by Write Throughput",
   "type": "stat",
   "description": "Throughput of top $TopResources volumes.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  topk(\n    $TopResources,\n    lun_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Luns by Read IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  topk(\n    $TopResources,\n    lun_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Top $TopResources Luns by Write IOPs",
   "type": "stat",
   "description": "IOPs of top $TopResources volumes.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  topk(\n    $TopResources,\n    lun_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "LUN Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Luns by Read Latency",
     "type": "table",
     "description": "Average read latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    lun_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"} @ end()\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read Throughput",
     "type": "table",
     "description": "Read bytes.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    lun_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"} @ end()\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read IOPS",
     "type": "table",
     "description": "Number of read operations.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    lun_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"} @ end()\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write Latency",
     "type": "table",
     "description": "Average write latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    lun_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"} @ end()\n  )",
       "legendFormat": "{{svm}}/{{volume}}/{{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write Throughput",
     "type": "table",
     "description": "Write bytes.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    lun_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"} @ end()\n  )"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write IOPS",
     "type": "table",
     "description": "Number of write operations.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    lun_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"} @ end()\n  )"
      }
     ]
    },
    {
     "title": "LUNS in Cluster",
     "type": "table",
     "description": "LUN details.\n\nNote: Block Size will be blank when there are no iops or throughput on the lun.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "lun_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "lun_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "lun_size{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "lun_size_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "lun_block_size{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top LUN Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Luns by Average Read Latency",
     "type": "timeseries",
     "description": "Average read latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read Throughput",
     "type": "timeseries",
     "description": "Read bytes.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read IOPs",
     "type": "timeseries",
     "description": "Number of read operations.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Average Write Latency",
     "type": "timeseries",
     "description": "Average write latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write Throughput",
     "type": "timeseries",
     "description": "Write bytes.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Write IOPs",
     "type": "timeseries",
     "description": "Number of write operations.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Block Size",
     "type": "timeseries",
     "description": "Represents the block size being used.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "lun_block_size{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_block_size{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top LUN Performance Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Luns by Write Misalignment Buckets",
     "type": "timeseries",
     "description": "Histogram of WAFL write alignment (number of sectors off WAFL block start).",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "lun_write_align_histo{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_write_align_histo{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} : {{metric}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Read Misalignment Buckets",
     "type": "timeseries",
     "description": "Histogram of WAFL read alignment (number sectors off WAFL block start).",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "lun_read_align_histo{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_read_align_histo{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} : {{metric}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Luns by Indirect Access IOPS",
     "type": "timeseries",
     "description": "Number of operations received by a storage system that does not own the LUN targeted by the operations.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_remote_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_remote_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Top Volume and LUN Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Volumes by Used %",
     "type": "timeseries",
     "description": "percentage of utilized storage space in a volume relative to its total capacity.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_size_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_size_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Snapshot Used %",
     "type": "timeseries",
     "description": "Percentage of snapshot reserve size that has been used.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_snapshot_reserve_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_snapshot_reserve_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Deduplication Percent Saved",
     "type": "timeseries",
     "description": "Percentage of the total disk space that is saved by deduplication and file cloning.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_sis_dedup_saved_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_sis_dedup_saved_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Volumes by Compression Percent Saved",
     "type": "timeseries",
     "description": "Percentage of the total disk space that is saved by compressing blocks on the referenced file system.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "volume_sis_compress_saved_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      volume_sis_compress_saved_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}}"
      }
     ]
    },
    {
     "title": "Top $TopResources LUNs by Percent Most Filled",
     "type": "timeseries",
     "description": "LUN used percent.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lun_size_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      lun_size_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "Top $TopResources LUNs by Percent Least Filled",
     "type": "timeseries",
     "description": "LUN used percent.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "lun_size_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\nand\n  bottomk(\n    $TopResources,\n    avg_over_time(\n      lun_size_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per LUN (Must Select Cluster/SVM/Volume/LUN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency",
     "type": "timeseries",
     "description": "This panels displays average read/write latency in microseconds for all operations on the LUN.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "lun_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "description": "This panel displays Read/Write bytes data.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "IOPs",
     "type": "timeseries",
     "description": "This panel displays number of read/write operations.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "lun_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    },
    {
     "title": "Indirect Access",
     "type": "timeseries",
     "description": "This panel displays detail of I/O to or from a LUN which is not owned by the storage system handling the I/O and number of operations received by a storage system that does not own the LUN targeted by the operations.",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "lun_remote_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Remote Data"
      },
      {
       "expr": "lun_remote_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Remote IOPs"
      }
     ]
    },
    {
     "title": "vStorage Offload Operations",
     "type": "timeseries",
     "description": "This panel displays detail of number of compare and write requests, number of unmap command requests, number of write same command requests, number of write same commands requests with unmap bit set and total number of xcopy operations on the LUN.",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "lun_caw_reqs{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "Compare and Write {{svm}} / {{volume}} / {{lun}}"
      },
      {
       "expr": "lun_unmap_reqs{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "Unmap {{svm}} / {{volume}} / {{lun}}"
      },
      {
       "expr": "lun_writesame_reqs{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "Write Same {{svm}} / {{volume}} / {{lun}}"
      },
      {
       "expr": "lun_writesame_unmap_reqs{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "Write Same Unmap {{svm}} / {{volume}} / {{lun}}"
      },
      {
       "expr": "lun_xcopy_reqs{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "Xcopy {{svm}} / {{volume}} / {{lun}}"
      }
     ]
    },
    {
     "title": "IO Size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "lun_read_data\n  /\n    lun_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\n/\n  1024",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Read"
      },
      {
       "expr": "lun_write_data\n  /\n    lun_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",lun=~\"$LUN\",svm=~\"$SVM\",volume=~\"$Volume|\",netapp_cluster=~\"$NetappCluster\"}\n/\n  1024",
       "legendFormat": "{{svm}} / {{volume}} / {{lun}} Write"
      }
     ]
    }
   ]
  }
 ]
}