{
 "title": "ONTAP: NVMe Namespaces",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(svm_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}, volume)"
    }
   },
   {
    "name": "Path",
    "query": {
     "query": "label_values(namespace_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\", volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},path)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  {
   "title": "Top NVMe Namespaces Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Top $TopResources NVMe Namespaces by Average Read Latency",
   "type": "timeseries",
   "description": "Average read latency in microseconds for all operations on the Namespace.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "namespace_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      namespace_avg_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{path}}"
    }
   ]
  },
  {
   "title": "Top $TopResources NVMe Namespaces by Read Throughput",
   "type": "timeseries",
   "description": "Read bytes.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "namespace_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      namespace_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{path}}"
    }
   ]
  },
  {
   "title": "Top $TopResources NVMe Namespaces by Read IOPs",
   "type": "timeseries",
   "description": "Number of read operations.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "namespace_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      namespace_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{path}}"
    }
   ]
  },
  {
   "title": "Top $TopResources NVMe Namespaces by Average Write Latency",
   "type": "timeseries",
   "description": "Average write latency in microseconds for all operations on the Namespace.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "namespace_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      namespace_avg_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{path}}"
    }
   ]
  },
  {
   "title": "Top $TopResources NVMe Namespaces by Write Throughput",
   "type": "timeseries",
   "description": "Write bytes.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "namespace_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      namespace_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{path}}"
    }
   ]
  },
  {
   "title": "Top $TopResources NVMe Namespaces by Write IOPs",
   "type": "timeseries",
   "description": "Number of write operations.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "namespace_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      namespace_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{path}}"
    }
   ]
  },
  {
   "title": "NVMe Namespaces Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "NVMe Namespaces",
     "type": "table",
     "description": "NVMe namespace details.",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "namespace_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "namespace_size_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "namespace_size{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "namespace_size_available_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",path=~\"$Path\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  }
 ]
}