{
 "title": "ONTAP: NFSv4 StorePool Monitors",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(node_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "You must enable the nfsv4_pool.yaml section in your $HARVEST/conf/zapiperf/default.yaml file. Please see https://github.com/NetApp/harvest/discussions/1796 for more details."
   }
  },
  {
   "title": "Allocations over 50%",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocations over 50%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_DelegStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_DelegStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - DelegStateAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_ByteLockAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_ByteLockMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - ByteLockAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_ClientAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_ClientMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - ClientAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_CopyStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_CopyStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - CopyStateAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_ConnectionParentSessionReferenceAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_ConnectionParentSessionReferenceMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - ConnectionParentSessionReferenceAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_DelegAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_DelegMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - DelegAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_LockAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_LockMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - LockAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_LayoutStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_LayoutStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - LayoutStateAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_LockStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_LockStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - LockStateAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_OpenStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_OpenStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - OpenStateAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_OpenAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_OpenMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - OpenAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_OwnerAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_OwnerMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - OwnerAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_SessionConnectionHolderAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_SessionConnectionHolderMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - SessionConnectionHolderAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_SessionHolderAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_SessionHolderMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - SessionHolderAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_SessionAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_SessionMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - SessionAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_StateRefHistoryAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_StateRefHistoryMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - StateRefHistoryAlloc"
      },
      {
       "expr": "100\n  *\n    (\n        nfs_diag_storePool_StringAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n      /\n        nfs_diag_storePool_StringMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    )\n>\n  50",
       "legendFormat": "{{node}} - StringAlloc"
      }
     ]
    }
   ]
  },
  {
   "title": "Lock",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "ByteLockAlloc",
     "type": "timeseries",
     "description": "For each byte-range lock acquired by a client there is a resulting increment in allocation.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_ByteLockAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_ByteLockMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "ClientAlloc",
     "type": "timeseries",
     "description": "For each ClientID exchanged with the server/SVM, this allocation is incremented.\nNFS version 4 uses a value of clientid or stateid to represent the current state (instance) of client-held resources such as locks, opens, and host restarts. The client and server pass this state information between them on certain operations, allowing both to agree on the current instance of resources held by the client.\n\nhttps://www.ibm.com/docs/en/zos/2.2.0?topic=introduction-nfs-version-4-state.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_ClientAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_ClientMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "ConnectionParentSessionReferenceAlloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_ConnectionParentSessionReferenceAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_ConnectionParentSessionReferenceMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CopyStateAlloc",
     "type": "timeseries",
     "description": "When NFS copy offload (A feature was added in the Icehouse release of the NetApp unified driver that enables Image service images to be efficiently copied to a destination Block Storage volume) is used, this allocation is incremented.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_CopyStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_CopyStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "DelegAlloc",
     "type": "timeseries",
     "description": "For each Delegation lock type issued, this allocation is incremented.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_DelegAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_DelegMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "DelegStateAlloc",
     "type": "timeseries",
     "description": "When an allocation type includes ‘State’ in the title, an allocation is provided for each StateID associated per the associated lock type.  In this case, when a Delegation type lock is acquired and associated with a specific StateID.  This is incremented once per Delegation type lock.\n\nStateIDs as defined in RFC 5661 –\n8.2.  Stateid Definition\n\n   When the server grants a lock of any type (including opens, byte-\n   range locks, delegations, and layouts), it responds with a unique\n   stateid that represents a set of locks (often a single lock) for the\n   same file, of the same type, and sharing the same ownership\n   characteristics.  Thus, opens of the same file by different open-\n   owners each have an identifying stateid.  Similarly, each set of\n   byte-range locks on a file owned by a specific lock-owner has its own\n   identifying stateid.  Delegations and layouts also have associated\n   stateids by which they may be referenced.  The stateid is used as a\n   shorthand reference to a lock or set of locks, and given a stateid,\n   the server can determine the associated state-owner or state-owners\n   (in the case of an open-owner/lock-owner pair) and the associated\n   filehandle.  When stateids are used, the current filehandle must be\n   the one associated with that stateid.\n.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_DelegStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_DelegStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "LayoutAlloc",
     "type": "timeseries",
     "description": "The LayoutAlloc is incremented for each Parallel NFS (pNFS) referral.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_LayoutAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_LayoutMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "LayoutStateAlloc",
     "type": "timeseries",
     "description": "LayoutStateAlloc is incremented for each StateID associated with each pNFS referral.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_LayoutStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_LayoutStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "LockStateAlloc",
     "type": "timeseries",
     "description": "LockStateAlloc is incremented for the last lock request and response on a given state-owner while the lock state exists on the server.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_LockStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_LockStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "OpenAlloc",
     "type": "timeseries",
     "description": "OpenAlloc is incremented for each Open request.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_OpenAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_OpenMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "OpenStateAlloc",
     "type": "timeseries",
     "description": "OpenStateAlloc is incremented for each StateID associated with each Open request.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_OpenStateAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_OpenStateMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "OwnerAlloc",
     "type": "timeseries",
     "description": "OwnerAlloc is incremented for Owner allocation information such as file name space, file information, chunk information and chunk allocation information. (source - https://dzone.com/articles/overview-and-recommendations).",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_OwnerAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_OwnerMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "SessionConnectionHolderAlloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_SessionConnectionHolderAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_SessionConnectionHolderMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "SessionHolderAlloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_SessionHolderAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_SessionHolderMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "SessionAlloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_SessionAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_SessionMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "StateRefHistoryAlloc",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_StateRefHistoryAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_StateRefHistoryMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "StringAlloc",
     "type": "timeseries",
     "description": "StringAlloc is incremented for each individual client co_ownerid. \n\nSee section 2.4 of RFC 5661 for more information regarding client generated co_ownerid strings\n.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100\n*\n  (\n      nfs_diag_storePool_StringAlloc{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n    /\n      nfs_diag_storePool_StringMax{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",node=~\"$Node\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  }
 ]
}