{
 "title": "ONTAP: Power",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Important Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard requires ONTAP 9.6+ and REST private CLI.\n\nSee <a target='blank' href='https://netapp.github.io/harvest/latest/power-algorithm'>power algorithm</a> for more details.\n\nPower and temperature metrics may not be visible for clusters with **embedded** disk shelves. Those metrics are computed at the cluster level, not at the level of individual shelves. Embedded shelf power is shared among the common nodes."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Total Power",
   "type": "stat",
   "description": "This panel displays total power of nodes and shelves.",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) or vector(0))\n+\n  (\n      sum(\n          shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n        * on (datacenter, cluster, shelf)\n          shelf_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEmbedded=\"No\",netapp_cluster=~\"$NetappCluster\"}\n      )\n    or\n      vector(0)\n  )"
    }
   ]
  },
  {
   "title": "Average Power/Used_TB",
   "type": "stat",
   "description": "Average Power per used TB.",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Watts/TB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n      (avg(environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) or vector(0))\n    +\n      avg(\n          (\n              shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n            * on (datacenter, cluster, shelf)\n              shelf_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEmbedded=\"No\",netapp_cluster=~\"$NetappCluster\"}\n          )\n        or\n          vector(0)\n      )\n  )\n/\n  (\n          (sum(aggr_space_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) / 1024 / 1024 / 1024 / 1024)\n        /\n          count(sum(node_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}))\n      >\n        1\n    or\n      max(\n          aggr_space_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n        /\n          aggr_space_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n      )\n  )"
    }
   ]
  },
  {
   "title": "Max Node Temp",
   "type": "stat",
   "description": "Maximum temperature of all non-ambient sensors for node in Celsius.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(environment_sensor_max_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Max Shelf Fan Speed",
   "type": "stat",
   "description": "Maximum fan speed for shelf in rpm.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelf_max_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Average IOPs/Watt",
   "type": "stat",
   "description": "Average IOPs Per Watt.",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "IOPs/Watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_total_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})\n/\n  (\n      (\n          (avg(environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) or vector(0))\n        +\n          avg(\n              (\n                  shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n                * on (datacenter, cluster, shelf)\n                  shelf_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEmbedded=\"No\",netapp_cluster=~\"$NetappCluster\"}\n              )\n            or\n              vector(0)\n          )\n      )\n    or\n      vector(1)\n  )"
    }
   ]
  },
  {
   "title": "Max Shelf Temp",
   "type": "stat",
   "description": "Maximum temperature of all non-ambient sensors for shelf in Celsius.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(shelf_max_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Max Node Fan Speed",
   "type": "stat",
   "description": "Maximum fan speed for node in rpm.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(environment_sensor_max_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Total Power Consumed",
   "type": "timeseries",
   "description": "This panel displays total power consumed by Node, Shelf and both.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum(environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})",
     "legendFormat": "Node"
    },
    {
     "expr": "sum(shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})",
     "legendFormat": "Shelf"
    },
    {
     "expr": "(sum(environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) or vector(0))\n+\n  (\n      sum(\n          shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n        * on (datacenter, cluster, shelf)\n          shelf_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEmbedded=\"No\",netapp_cluster=~\"$NetappCluster\"}\n      )\n    or\n      vector(0)\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Average Power Consumption (kWh) Over Last Hour",
   "type": "timeseries",
   "description": "This panel displays the average power consumption in kilowatt-hours (kWh) over the last hour for Nodes, Shelves, and the total combined.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[1h]))",
     "legendFormat": "Node"
    },
    {
     "expr": "sum(avg_over_time(shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[1h]))",
     "legendFormat": "Shelf"
    },
    {
     "expr": "sum(avg_over_time(environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[1h]))\n+\n  sum(\n      avg_over_time(shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[1h])\n    * on (datacenter, cluster, shelf)\n      shelf_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEmbedded=\"No\",netapp_cluster=~\"$NetappCluster\"}\n  )",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Power Consumed",
   "type": "timeseries",
   "description": "Power consumed by a node in Watts.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end())\n  )",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Nodes by Average Temperature",
   "type": "timeseries",
   "description": "Average temperature of all non-ambient sensors for node in Celsius.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "environment_sensor_average_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      environment_sensor_average_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Shelves by Power Consumed",
   "type": "timeseries",
   "description": "Power consumed by shelf in Watts.",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk($TopResources, avg_over_time(shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()))",
     "legendFormat": "{{shelf}} ({{netapp_cluster}})"
    }
   ]
  },
  {
   "title": "Top $TopResources Shelves by Average Temperature",
   "type": "timeseries",
   "description": "Average temperature of all non-ambient sensors for shelf in Celsius.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "shelf_average_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(shelf_average_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end())\n  )",
     "legendFormat": "{{shelf}} ({{netapp_cluster}})"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by Power Consumed",
   "type": "timeseries",
   "description": "View the power usage at the aggregate level, track down any \"hot\" aggregates and their corresponding workloads.\n\nThe line chart provides the ability to see how read/write IOs directly affect the power usage of the system. .",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "aggr_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk($TopResources, avg_over_time(aggr_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()))",
     "legendFormat": "{{netapp_cluster}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Aggregates Power by Disk Type",
   "type": "timeseries",
   "description": "Power used across your Aggregate disk types.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (derivedType, cluster) (aggr_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})",
     "legendFormat": "{{netapp_cluster}} - {{derivedType}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Aggregates by IOPS Per Power Consumed",
   "type": "timeseries",
   "description": "Provides the ability to see how read/write IOs directly affect the power usage of the system.",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "(\n    sum by (datacenter, cluster, aggr) (\n      aggr_disk_user_reads{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n    )\n  )\nand on (datacenter, cluster, aggr)\n  topk(\n    $TopResources,\n    sum by (datacenter, cluster, aggr) (\n      avg_over_time(aggr_disk_user_reads{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[3h])\n    )\n  )",
     "legendFormat": "Reads  - {{netapp_cluster}} - {{aggr}}"
    },
    {
     "expr": "(\n    sum by (datacenter, cluster, aggr) (\n      aggr_disk_user_writes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n    )\n  )\nand on (datacenter, cluster, aggr)\n  topk(\n    $TopResources,\n    sum by (datacenter, cluster, aggr) (\n      avg_over_time(aggr_disk_user_writes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}[3h])\n    )\n  )",
     "legendFormat": "Writes  - {{netapp_cluster}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Aggregate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregates",
     "type": "table",
     "description": "Aggregate details.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "aggr_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "sum by (aggr, cluster, node) (\n  aggr_disk_total_transfers{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "sum by (aggr, cluster, node) (aggr_disk_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Sensor Problems",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sensor Problems",
     "type": "table",
     "description": "Displays sensors with failed state.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "environment_sensor_threshold_value{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",threshold_state!=\"normal\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Field Replaceable Unit (FRU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
     "options": {
      "content": "This panel requires a cluster with ONTAP 9.6+ and the Harvest REST collector."
     }
    },
    {
     "title": "Field Replaceable Unit (FRU)",
     "type": "table",
     "description": "Displays information about the status of Field Replaceable Units (FRUs).",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "fru_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Nodes",
     "type": "table",
     "description": "Storage node details.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_average_ambient_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_min_ambient_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_max_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_average_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_min_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_max_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_average_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "environment_sensor_min_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shelves",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Shelves",
     "type": "table",
     "description": "Storage shelf details.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "shelf_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_disk_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_new_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_power{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n* on (datacenter, cluster, shelf)\n  shelf_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEmbedded=\"No\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_average_ambient_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_min_ambient_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_max_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_average_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_min_temperature{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_max_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_average_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "shelf_min_fan_speed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  }
 ]
}