{
 "title": "ONTAP: Qtree",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(qtree_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, svm)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(qtree_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\", svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}, volume)"
    }
   },
   {
    "name": "Qtree",
    "query": {
     "query": "label_values(qtree_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\", svm=~\"$SVM\", volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}, qtree)"
    }
   },
   { "name": "TopResources", "query": "1,2,3,4,5,6,8,10,15,20,40" }
  ]
 },
 "panels": [
  {
   "title": "Important Information about Qtree dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard requires enabling a qtree template. <br>Please see [How to enable qtree templates](https://github.com/NetApp/harvest/discussions/3446) for more details. Enabling `qtree.yaml` may slow down data collection."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Top $TopResources NFSs by IOPs",
   "type": "timeseries",
   "description": "Number of NFS operations per second to the qtree.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "qtree_nfs_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qtree_nfs_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}} - {{qtree}}"
    }
   ]
  },
  {
   "title": "Top $TopResources CIFS by IOPs",
   "type": "timeseries",
   "description": "Number of CIFS operations per second to the qtree.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "qtree_cifs_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qtree_cifs_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}} - {{qtree}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Qtrees by IOPs",
   "type": "timeseries",
   "description": "Summation of NFS ops, CIFS ops, CSS ops and internal ops.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "qtree_total_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qtree_total_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}} - {{qtree}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Qtrees by Internal IOPs",
   "type": "timeseries",
   "description": "Number of internal operations generated by activites such as snapmirror and backup per second to the qtree.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "qtree_internal_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qtree_internal_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{svm}} - {{volume}} - {{qtree}}"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Qtrees by Disk Used",
     "type": "timeseries",
     "description": "Current amount of disk space, in kilobytes, used by the quota target.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "quota_disk_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      quota_disk_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{qtree}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Qtrees by Files Used",
     "type": "timeseries",
     "description": "Current number of files used by the quota target.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "quota_files_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      quota_files_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{qtree}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Qtrees by Disk Used Growth",
     "type": "timeseries",
     "description": "Current amount of disk space, in kilobytes, used by the quota target.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "KiBs" } },
     "targets": [
      {
       "expr": "quota_disk_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      quota_disk_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{svm}} - {{volume}} - {{qtree}}"
      }
     ]
    }
   ]
  }
 ]
}