{
 "title": "ONTAP: Quota",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(svm_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, svm)"
    }
   },
   {
    "name": "Tag",
    "label": "Volume Tag",
    "query": {
     "query": "label_values(volume_tags{datacenter=~\"$Datacenter\", cluster=~\"$Cluster\", svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"},tag)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(volume_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",svm=~\"$SVM\",style!=\"flexgroup_constituent\",tags=~\".*$Tag.*\",netapp_cluster=~\"$NetappCluster\"}, volume)"
    }
   },
   {
    "name": "Qtree",
    "query": {
     "query": "query_result(quota_disk_limit{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\", svm=~\"$SVM\",volume=~\"$Volume\"} * on (datacenter, cluster, svm, volume) group_left(tags) volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\"})"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Important Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<br>By default, only `tree` type quotas are collected via Harvest. If you wish to collect user and group quotas as well, please follow the steps outlined at [GitHub discussion #2911](https://github.com/NetApp/harvest/discussions/2911)."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Reports",
   "type": "table",
   "description": "Only tree quotas are shown by default. To collect user/group quotas, enable them in the qtree.yaml template.",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "label_join(\n    quota_disk_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  * on (datacenter, cluster, svm, volume) group_left (tags)\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"svm\",\n  \"volume\",\n  \"qtree\",\n  \"group\",\n  \"user\"\n)"
    },
    {
     "expr": "label_join(\n    quota_disk_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  * on (datacenter, cluster, svm, volume) group_left (tags)\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"svm\",\n  \"volume\",\n  \"qtree\",\n  \"group\",\n  \"user\"\n)"
    },
    {
     "expr": "label_join(\n    quota_file_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  * on (datacenter, cluster, svm, volume) group_left (tags)\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"svm\",\n  \"volume\",\n  \"qtree\",\n  \"group\",\n  \"user\"\n)"
    },
    {
     "expr": "label_join(\n    quota_files_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  * on (datacenter, cluster, svm, volume) group_left (tags)\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"svm\",\n  \"volume\",\n  \"qtree\",\n  \"group\",\n  \"user\"\n)"
    },
    {
     "expr": "label_join(\n    quota_soft_disk_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  * on (datacenter, cluster, svm, volume) group_left (tags)\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"svm\",\n  \"volume\",\n  \"qtree\",\n  \"group\",\n  \"user\"\n)"
    },
    {
     "expr": "label_join(\n    quota_disk_used_pct_disk_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  * on (datacenter, cluster, svm, volume) group_left (tags)\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"svm\",\n  \"volume\",\n  \"qtree\",\n  \"group\",\n  \"user\"\n)"
    },
    {
     "expr": "label_join(\n    quota_files_used_pct_file_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  * on (datacenter, cluster, svm, volume) group_left (tags)\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"svm\",\n  \"volume\",\n  \"qtree\",\n  \"group\",\n  \"user\"\n)"
    },
    {
     "expr": "label_join(\n    quota_soft_file_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  * on (datacenter, cluster, svm, volume) group_left (tags)\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"},\n  \"index\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"svm\",\n  \"volume\",\n  \"qtree\",\n  \"group\",\n  \"user\"\n)"
    }
   ]
  },
  {
   "title": "Space Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Quotas by Space Used",
     "type": "timeseries",
     "description": "The amount of space used in qtree.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "quota_disk_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n      max without (tags) (\n        avg_over_time(\n          quota_disk_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h]\n        )\n      )\n    * on (datacenter, cluster, svm, volume) group_left ()\n      volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{volume}} - {{qtree}} - {{type}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Quotas by Space Used %",
     "type": "timeseries",
     "description": "The amount of space used % in qtree.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "quota_disk_used_pct_disk_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n      max without (tags) (\n        avg_over_time(\n          quota_disk_used_pct_disk_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h]\n        )\n      )\n    * on (datacenter, cluster, svm, volume) group_left ()\n      volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{volume}} - {{qtree}} - {{type}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Quotas by Files Used",
     "type": "timeseries",
     "description": "The number of files used in qtree.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "quota_files_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n      max without (tags) (\n        avg_over_time(\n          quota_files_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h]\n        )\n      )\n    * on (datacenter, cluster, svm, volume) group_left ()\n      volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{volume}} - {{qtree}} - {{type}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Quotas by Files Used %",
     "type": "timeseries",
     "description": "The number of files used % in qtree.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "quota_files_used_pct_file_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n      max without (tags) (\n        avg_over_time(\n          quota_files_used_pct_file_limit{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",qtree=~\"$Qtree\",svm=~\"$SVM\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}[3h]\n        )\n      )\n    * on (datacenter, cluster, svm, volume) group_left ()\n      volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",tags=~\".*$Tag.*\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  )",
       "legendFormat": "{{volume}} - {{qtree}} - {{type}}"
      }
     ]
    }
   ]
  }
 ]
}