{
 "title": "ONTAP: Security",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "fsx"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"},cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(svm_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",root_svm=\"No\",netapp_cluster=~\"$NetappCluster\"},svm)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Important Information about Security dashboard",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "View ONTAP Security Hardening Guide https://www.netapp.com/fr/media/10674-tr4569.pdf for more details."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Cluster Compliant %",
   "type": "stat",
   "description": "Percentage of clusters which are compliant.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    group by (datacenter, cluster) (\n                                support_labels{asup_enabled=\"true\",asup_https_configured!=\"https\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n                              or\n                                security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",telnet_enabled=\"true\",netapp_cluster=~\"$NetappCluster\"}\n                            or\n                              security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",rsh_enabled=\"true\",netapp_cluster=~\"$NetappCluster\"}\n                          or\n                              group by (datacenter, cluster) (\n                                security_account_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",hash_algorithm=\"md5\",netapp_cluster=~\"$NetappCluster\"}\n                              )\n                            >\n                              0\n                        or\n                          cluster_peer_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",encryption_state=\"\",netapp_cluster=~\"$NetappCluster\"}\n                      or\n                        cluster_peer_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",encryption_state=\"none\",netapp_cluster=~\"$NetappCluster\"}\n                    or\n                        group by (datacenter, cluster) (\n                          security_account_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",locked=\"false\",netapp_cluster=~\"$NetappCluster\"}\n                        )\n                      >\n                        0\n                  or\n                    security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"cluster\",netapp_cluster=~\"$NetappCluster\"}\n                or\n                  security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}\n              or\n                count by (datacenter, cluster) (ntpserver_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) < 1\n            or\n              security_audit_destination_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protocol!=\"tcp_encrypted\",netapp_cluster=~\"$NetappCluster\"}\n          or\n            security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",fips_enabled=\"false\",netapp_cluster=~\"$NetappCluster\"}\n        or\n          svm_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",type=\"admin\",netapp_cluster=~\"$NetappCluster\"}\n      or\n        group by (datacenter, cluster) (\n                (\n                    svm_labels{cifs_protocol_enabled=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                  or\n                      svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nfs_protocol_enabled=\"true\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                    and\n                      svm_labels{audit_protocol_enabled=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                )\n              or\n                security_ssh_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n            or\n              security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"svm\",netapp_cluster=~\"$NetappCluster\"}\n          or\n            security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n        )\n    )\n  )\nor\n  vector(0)",
     "legendFormat": "NonCompliantCluster"
    },
    {
     "expr": "count(security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) or vector(1)",
     "legendFormat": "TotalCluster"
    }
   ]
  },
  {
   "title": "SVM Compliant %",
   "type": "stat",
   "description": "Percentage of SVMs which are compliant.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    group by (datacenter, cluster, svm) (\n            (\n                svm_labels{cifs_protocol_enabled=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n              or\n                  svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nfs_protocol_enabled=\"true\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                and\n                  svm_labels{audit_protocol_enabled=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n            )\n          or\n            svm_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n        or\n          security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"svm\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      or\n        (\n            svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n          unless on (svm)\n            security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm!=\"$Cluster\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n        )\n    )\n  )\nor\n  vector(0)",
     "legendFormat": "NonCompliantSvm"
    },
    {
     "expr": "count(svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}) or vector(1)",
     "legendFormat": "TotalSvm"
    }
   ]
  },
  {
   "title": "Volume Encryption %",
   "type": "stat",
   "description": "Percentage of volumes which are encrypted.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n      count(\n        volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEncrypted=\"true\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      )\n    or\n      vector(0)\n  )\n+\n  (\n      count(\n        volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isHardwareEncrypted=\"true\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      )\n    or\n      vector(0)\n  )",
     "legendFormat": "encrypted"
    },
    {
     "expr": "(\n    count(volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})\n  or\n    vector(1)\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Volume Autonomous Ransomware Protection %",
   "type": "stat",
   "description": "Percentage of volumes which are anti-ransomware enabled.",
   "gridPos": { "h": 3, "w": 4.5, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n      (\n          count(\n            volume_labels{antiRansomwareState!=\"\",antiRansomwareState=~\"enabled|dry_run\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n          )\n        or\n          vector(0)\n      )\n    /\n      (\n          count(\n            volume_labels{antiRansomwareState!=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n          )\n        or\n          vector(1)\n      )\n  )\n*\n  100"
    }
   ]
  },
  {
   "title": "SVM Autonomous Ransomware Protection %",
   "type": "stat",
   "description": "Percentage of SVMs which are anti-ransomware enabled.",
   "gridPos": { "h": 3, "w": 4.5, "x": 19.5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n      (\n          count(\n            svm_labels{anti_ransomware_state!=\"\",anti_ransomware_state=~\"enabled|dry_run\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n          )\n        or\n          vector(0)\n      )\n    /\n      (\n          count(\n            svm_labels{anti_ransomware_state!=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n          )\n        or\n          vector(1)\n      )\n  )\n*\n  100"
    }
   ]
  },
  {
   "title": "Cluster Compliant",
   "type": "piechart",
   "description": "This panel displays cluster compliant detail.",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) or vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(\n    group by (datacenter, cluster) (\n                                support_labels{asup_enabled=\"true\",asup_https_configured!=\"https\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n                              or\n                                security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",telnet_enabled=\"true\",netapp_cluster=~\"$NetappCluster\"}\n                            or\n                              security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",rsh_enabled=\"true\",netapp_cluster=~\"$NetappCluster\"}\n                          or\n                              group by (datacenter, cluster) (\n                                security_account_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",hash_algorithm=\"md5\",netapp_cluster=~\"$NetappCluster\"}\n                              )\n                            >\n                              0\n                        or\n                          cluster_peer_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",encryption_state=\"\",netapp_cluster=~\"$NetappCluster\"}\n                      or\n                        cluster_peer_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",encryption_state=\"none\",netapp_cluster=~\"$NetappCluster\"}\n                    or\n                        group by (datacenter, cluster) (\n                          security_account_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",locked=\"false\",netapp_cluster=~\"$NetappCluster\"}\n                        )\n                      >\n                        0\n                  or\n                    security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"cluster\",netapp_cluster=~\"$NetappCluster\"}\n                or\n                  security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}\n              or\n                count by (datacenter, cluster) (ntpserver_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) < 1\n            or\n              security_audit_destination_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protocol!=\"tcp_encrypted\",netapp_cluster=~\"$NetappCluster\"}\n          or\n            security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",fips_enabled=\"false\",netapp_cluster=~\"$NetappCluster\"}\n        or\n          svm_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",type=\"admin\",netapp_cluster=~\"$NetappCluster\"}\n      or\n        group by (datacenter, cluster) (\n                (\n                    svm_labels{cifs_protocol_enabled=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                  or\n                      svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nfs_protocol_enabled=\"true\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                    and\n                      svm_labels{audit_protocol_enabled=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                )\n              or\n                security_ssh_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n            or\n              security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"svm\",netapp_cluster=~\"$NetappCluster\"}\n          or\n            security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n        )\n    )\n  )\nor\n  vector(0)",
     "legendFormat": "Non Compliant"
    }
   ]
  },
  {
   "title": "SVM Compliant",
   "type": "piechart",
   "description": "This panel displays SVM compliant detail.",
   "gridPos": { "h": 13, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}) or vector(1)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(\n  group by (datacenter, cluster, svm) (\n          (\n              svm_labels{cifs_protocol_enabled=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n            or\n                svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nfs_protocol_enabled=\"true\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n              and\n                svm_labels{audit_protocol_enabled=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n          )\n        or\n          svm_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      or\n        security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"svm\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n    or\n      (\n          svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n        unless on (svm)\n          security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm!=\"$Cluster\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      )\n  )\n)",
     "legendFormat": "Not Compliant"
    }
   ]
  },
  {
   "title": "Volume Encryption",
   "type": "piechart",
   "description": "This panel displays volume encryption detail.",
   "gridPos": { "h": 13, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEncrypted=\"true\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Software"
    },
    {
     "expr": "count(\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isHardwareEncrypted=\"true\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Hardware"
    },
    {
     "expr": "count(\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEncrypted=\"true\",isHardwareEncrypted=\"true\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Hardware and Software"
    },
    {
     "expr": "count(\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isEncrypted=\"false\",isHardwareEncrypted=\"false\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Not Encrypted"
    }
   ]
  },
  {
   "title": "Volume Autonomous Ransomware Protection",
   "type": "piechart",
   "description": "This panel requires the Harvest REST collector and an ONTAP 9.10+ cluster with autonomous ransomware protection enabled.\n<br>\n\nSee <a target='blank' href='https://docs.netapp.com/us-en/ontap/anti-ransomware/enable-task.html'>Enable ARP</a> for more details<br>.",
   "gridPos": { "h": 13, "w": 4.5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n    volume_labels{antiRansomwareState!=\"\",antiRansomwareState=\"enabled\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Enabled in active mode"
    },
    {
     "expr": "count(\n    volume_labels{antiRansomwareState!=\"\",antiRansomwareState=\"dry_run\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Enabled in learning mode"
    },
    {
     "expr": "count(\n    volume_labels{antiRansomwareState!=\"\",antiRansomwareState=~\".*paused.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Paused"
    },
    {
     "expr": "count(\n    volume_labels{antiRansomwareState!=\"\",antiRansomwareState=~\"disabled\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Disabled"
    }
   ]
  },
  {
   "title": "SVM Autonomous Ransomware Protection",
   "type": "piechart",
   "description": "This panel displays SVM anti ransomware detail.",
   "gridPos": { "h": 13, "w": 4.5, "x": 19.5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(\n    svm_labels{anti_ransomware_state!=\"\",anti_ransomware_state=~\"enabled|dry_run\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Enabled"
    },
    {
     "expr": "count(\n    svm_labels{anti_ransomware_state!=\"\",anti_ransomware_state=~\"disabled\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Disabled"
    }
   ]
  },
  { "title": "Cluster Authentication Methods", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Authentication Methods", "type": "text", "gridPos": { "h": 1, "w": 16, "x": 0, "y": 20 } },
  { "title": "Admin Certificates", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 16, "y": 20 } },
  {
   "title": "SAML",
   "type": "stat",
   "description": "Number of SAML authentication.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    count by (datacenter, cluster) (\n      security_account_samluser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"} > 0\n    )\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "AD/LDAP",
   "type": "stat",
   "description": "Number of AD & LDAP authentication.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n      count(\n        count by (datacenter, cluster) (\n          security_account_activediruser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"} > 0\n        )\n      )\n    +\n      count(\n        count by (datacenter, cluster) (\n          security_account_ldapuser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"} > 0\n        )\n      )\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Certificate",
   "type": "stat",
   "description": "Number of certificate authentication.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    count by (datacenter, cluster) (\n      security_account_certificateuser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"} > 0\n    )\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Local",
   "type": "stat",
   "description": "Number of password authentication.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    count by (datacenter, cluster) (\n      security_account_localuser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"} > 0\n    )\n  )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Expiring in < 60 days",
   "type": "stat",
   "description": "Number of certificates expiring within 60 days.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  security_certificate_labels{certificateExpiryStatus=\"expiring\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
    }
   ]
  },
  {
   "title": "Expired",
   "type": "stat",
   "description": "Number of certificates expired.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  security_certificate_labels{certificateExpiryStatus=\"expired\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
    }
   ]
  },
  {
   "title": "SSL Certificates Expiration",
   "type": "table",
   "description": "This panel displays SSL Certificate expiration time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "security_certificate_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",expiry_time!=\"\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "security_certificate_expiry_time{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"} - time()"
    }
   ]
  },
  {
   "title": "Volume Encryption & Autonomous Ransomware Protection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume Encryption & Autonomous Ransomware Protection",
     "type": "table",
     "description": "Volume encryption & Autonomous ransomware Protection.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    },
    {
     "title": "Anti-ransomware Snapshots",
     "type": "table",
     "description": "Detail of anti-ransomware snapshot.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "snapshot_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "snapshot_restore_size{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "snapshot_create_time{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Compliance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Compliance",
     "type": "table",
     "description": "❌  means this attribute is non-compliant. \n\n|  Column  | Compliant When  |  \n|---|---|\n| `Snapshot Policy` | All volumes have applied Snapshot policy |  \n| `Snapshot Autodelete` | All volumes have enabled Snapshot autodelete |\n| `ARW Protection for SVMs` | All SVMs have enabled ARW protection |\n|`ARW Protection for Volumes`| All volumes have enabled ARW protection|\n| `Cluster Certificate Validity` | Cluster has active certificate(s) |\n| `Global FIPS`| Cluster has global FIPS enabled |\n| `Telnet` | Cluster has telnet disabled |\n| `Autosupport Https Transport` | Cluster uses HTTPS for autosupport |\n| `Default Admin User` | Default admin user is locked |\n| `Remote Shell` | Cluster's remote shell is disabled |\n| `MD5 in use` | Cluster does not use MD5 algorithm |\n| `Insecure SSH Settings` | Cluster has strong SSH server ciphers |\n| `Login Banner` | Cluster has enabled login banner |\n| `Log Forwarding Encrypted` | Cluster has encrypted protocol for log forwarding |\n| `Network Time Protocol` | Cluster has configured three NTP servers |\n| `Cluster Peering` | Cluster peers use encryption |\n| `Notification Configured` | Cluster has configured destinations for notifications |\n| `Automatic Updates Configured`| Cluster has enabled automatic updates |.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "support_labels{asup_https_configured=\"https\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "group by (datacenter, cluster, locked) (\n  security_account_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",locked!=\"\",methods=~\".*password.*\",role_name=\"admin\",user_name=\"admin\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "count by (datacenter, cluster, hash_algorithm) (\n  security_account_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",hash_algorithm=\"md5\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "count by (datacenter, cluster, insecured) (\n  svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",insecured=\"true\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"cluster\",netapp_cluster=~\"$NetappCluster\"}\nor\n  security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "count by (datacenter, cluster) (ntpserver_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"})"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  cluster_peer_non_encrypted{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  security_account_localuser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  security_account_samluser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  security_account_activediruser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  security_account_ldapuser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  security_account_certificateuser{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "security_certificate_labels{certificateExpiryStatus!=\"\",certificateIssuerType!=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "group by (datacenter, cluster) (\n                            support_labels{asup_enabled=\"true\",asup_https_configured!=\"https\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n                          or\n                            security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",telnet_enabled=\"true\",netapp_cluster=~\"$NetappCluster\"}\n                        or\n                          security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",rsh_enabled=\"true\",netapp_cluster=~\"$NetappCluster\"}\n                      or\n                          group by (datacenter, cluster) (\n                            security_account_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",hash_algorithm=\"md5\",netapp_cluster=~\"$NetappCluster\"}\n                          )\n                        >\n                          0\n                    or\n                      cluster_peer_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",encryption_state=\"\",netapp_cluster=~\"$NetappCluster\"}\n                  or\n                    cluster_peer_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",encryption_state=\"none\",netapp_cluster=~\"$NetappCluster\"}\n                or\n                    group by (datacenter, cluster) (\n                      security_account_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",locked=\"false\",netapp_cluster=~\"$NetappCluster\"}\n                    )\n                  >\n                    0\n              or\n                security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"cluster\",netapp_cluster=~\"$NetappCluster\"}\n            or\n              security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}\n          or\n            count by (datacenter, cluster) (ntpserver_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}) < 1\n        or\n          security_audit_destination_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",protocol!=\"tcp_encrypted\",netapp_cluster=~\"$NetappCluster\"}\n      or\n        security_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",fips_enabled=\"false\",netapp_cluster=~\"$NetappCluster\"}\n    or\n      svm_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",type=\"admin\",netapp_cluster=~\"$NetappCluster\"}\n  or\n    group by (datacenter, cluster) (\n                        (\n                            svm_labels{cifs_protocol_enabled=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                          or\n                              svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nfs_protocol_enabled=\"true\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                            and\n                              svm_labels{audit_protocol_enabled=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                        )\n                      or\n                        security_ssh_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n                    or\n                      security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"svm\",netapp_cluster=~\"$NetappCluster\"}\n                  or\n                    security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                or\n                    sum by (datacenter, cluster) (\n                      volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",snapshot_policy=\"none\",netapp_cluster=~\"$NetappCluster\"}\n                    )\n                  >\n                    0\n              or\n                  sum by (datacenter, cluster) (\n                    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",snapshot_autodelete=\"true\",netapp_cluster=~\"$NetappCluster\"}\n                  )\n                >\n                  0\n            or\n                sum by (datacenter, cluster) (\n                  svm_labels{anti_ransomware_state=~\"|.*disabled\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n                )\n              >\n                0\n          or\n              volume_arw_status{ArwStatus!=\"Active Mode\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n            * on (instance) group_left ()\n              metadata_collector_instances{collector=\"Rest\",datacenter=~\"$Datacenter\",object=\"Volume\",netapp_cluster=~\"$NetappCluster\"}\n        or\n            count by (datacenter, cluster) (\n              ems_destination_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n            )\n          >\n            0\n      or\n        support_auto_update_labels{auto_update_enabled=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n    )\n)"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",snapshot_policy=\"none\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",root_volume=\"No\",snapshot_autodelete=\"true\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "sum by (datacenter, cluster) (\n  svm_labels{anti_ransomware_state=~\"|.*disabled\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "volume_arw_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n* on (instance) group_left ()\n  metadata_collector_instances{collector=\"Rest\",datacenter=~\"$Datacenter\",object=\"Volume\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "count by (datacenter, cluster) (\n  ems_destination_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "support_auto_update_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "security_audit_destination_status{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "SVM Compliance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "SVM Compliance",
     "type": "table",
     "description": "❌  means this attribute is non-compliant.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"svm\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nor\n  security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm!=\"$Cluster\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "count by (datacenter, cluster, insecured) (\n  svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",insecured=\"true\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)"
      },
      {
       "expr": "svm_ldap_signed{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "svm_ldap_encrypted{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      },
      {
       "expr": "group by (datacenter, cluster, svm) (\n        (\n            svm_labels{cifs_protocol_enabled=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n          or\n              svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",nfs_protocol_enabled=\"true\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n            and\n              svm_labels{audit_protocol_enabled=\"false\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n        )\n      or\n        svm_labels{ciphers=~\".*_cbc.*\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n    or\n      security_login_labels{banner=\"\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scope=\"svm\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  or\n    (\n        svm_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      unless on (svm)\n        security_login_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm!=\"$Cluster\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n    )\n)"
      }
     ]
    }
   ]
  }
 ]
}