{
 "title": "ONTAP: SMB",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(volume_labels{cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, svm)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Important Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "The `Highlights` section of this dashboard is dependent on the `CIFSSession` template. By default, these templates are disabled to prevent any potential slowdown in data collection, which can occur due to the processing of a large number of metrics. If you're using the Zapi/Rest collector, it's necessary to enable the `CIFSSession` template within its configuration settings."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Top $TopResources Connection Count",
   "type": "timeseries",
   "description": "The number of CIFS connections associated with the CIFS session.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cifs_session_connection_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      cifs_session_connection_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{svm}} - {{client_ip}} - {{protocol}}"
    }
   ]
  },
  {
   "title": "Connection Count By SMB version",
   "type": "timeseries",
   "description": "The number of CIFS connections associated with SMB version.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (protocol) (\n  cifs_session_connection_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "CIFS Sessions",
   "type": "table",
   "description": "Detail of CIFS sessions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "cifs_session_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "cifs_session_idle_duration{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
    }
   ]
  },
  {
   "title": "SMB Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read / Write IOPS",
     "type": "timeseries",
     "description": "This panel includes sum of read and write SMB OP’s /sec.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (cluster) (smb2_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "read_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "write_ops - {{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Read / Write Latency",
     "type": "timeseries",
     "description": "This panel includes average SMB read and write latency.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (cluster) (smb2_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "Read - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (smb2_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "Write - {{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Other IOPS",
     "type": "timeseries",
     "description": "This panel includes SMB OP’s /sec average broken down by other SMB operations.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (cluster) (smb2_negotiate_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "negotiate_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_session_setup_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "session_setup_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_tree_connect_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "tree_connect_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_create_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "create_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum(smb2_close_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "close_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_lock_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "lock_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (\n  smb2_query_directory_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)",
       "legendFormat": "query_directory_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_query_info_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "query_info_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_set_info_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "set_info_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_tree_connect_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "tree_connect_ops - {{netapp_cluster}}"
      },
      {
       "expr": "sum by (cluster) (smb2_oplock_break_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "oplock_break_ops - {{netapp_cluster}}"
      }
     ]
    },
    {
     "title": "Other Latency",
     "type": "timeseries",
     "description": "This panel includes SMB latency broken down by other SMB operations.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (cluster) (smb2_negotiate_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "negotiate_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (\n  smb2_session_setup_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)",
       "legendFormat": "session_setup_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (\n  smb2_tree_connect_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)",
       "legendFormat": "tree_connect_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (smb2_create_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "create_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (smb2_close_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "close_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (smb2_lock_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "lock_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (\n  smb2_query_directory_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)",
       "legendFormat": "query_directory_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (\n  smb2_query_info_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)",
       "legendFormat": "query_info_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (smb2_set_info_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"})",
       "legendFormat": "set_info_latency - {{netapp_cluster}}"
      },
      {
       "expr": "avg by (cluster) (\n  smb2_oplock_break_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n)",
       "legendFormat": "oplock_break_latency - {{netapp_cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heatmaps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "options": {
      "content": "These panels require that the eight `_histogram` counters be uncommented in the respective SMB2 template.<br>\n`RestPerf` template in `conf/restperf/9.14.1/smb2.yaml`<br> \n`ZapiPerf` template in `conf/zapiperf/cdot/9.8.0/smb2.yaml`<br>\nEnabling the SMB2 histogram counters may cause the poller to use more memory if there are a large number of histogram metrics to export."
     }
    },
    {
     "title": "Session Setup Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for Session Setups and gives good indication of Client Authentication Latency Breakdown.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (le) (\n  increase(\n    smb2_session_setup_latency_histogram_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Create Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for file opens and creates.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by (le) (\n  increase(\n    smb2_create_latency_histogram_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Close Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for file closes.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "sum by (le) (\n  increase(\n    smb2_close_latency_histogram_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Lock Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for file locks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "sum by (le) (\n  increase(\n    smb2_lock_latency_histogram_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Query Directory Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for readdir.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (le) (\n  increase(\n    smb2_query_directory_latency_histogram_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Query Info Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for getattr.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum by (le) (\n  increase(\n    smb2_query_info_latency_histogram_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Set Info Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for setattr.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum by (le) (\n  increase(\n    smb2_set_info_latency_histogram_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Oplock Break Latency Heatmap",
     "type": "heatmap",
     "description": "This panel tracks histograms for oplock breaks.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum by (le) (\n  increase(\n    smb2_oplock_break_latency_histogram_bucket{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[9d2m57s]\n  )\n)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}