{
 "title": "ONTAP: SnapMirror Sources",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"},datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "query_result(snapmirror_labels{system_type!=\"7mode\"} * on (source_volume, source_vserver, source_cluster) group_left() label_replace( label_replace( label_replace( volume_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, \"source_volume\", \"$1\", \"volume\", \"(.*)\") , \"source_vserver\", \"$1\", \"svm\", \"(.*)\"), \"source_cluster\", \"$1\", \"cluster\", \"(.*)\"))"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(snapmirror_labels{source_cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"},source_vserver)"
    }
   },
   {
    "name": "Volume",
    "query": {
     "query": "label_values(snapmirror_labels{source_cluster=~\"$Cluster\", source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"},source_volume)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Unhealthy Relationships",
   "type": "stat",
   "description": "Number of unhealthy snapmirrors.",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (relationship_id) (\n    snapmirror_labels{healthy=\"false\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\"$Volume\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\n)"
    }
   ]
  },
  {
   "title": "Number of Failed SnapMirror Transfers",
   "type": "stat",
   "description": "Total number of snapmirror transfers that have failed.",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n        snapmirror_break_failed_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      )\n    +\n      sum(\n        snapmirror_resync_failed_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      )\n  +\n    sum(\n      snapmirror_update_failed_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n    )\nor on ()\n  vector(0)"
    }
   ]
  },
  {
   "title": "Number of Successful SnapMirror Transfers",
   "type": "stat",
   "description": "Total number of snapmirror transfers that have been successfully completed without any errors or issues.",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n        snapmirror_break_successful_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      )\n    +\n      sum(\n        snapmirror_resync_successful_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      )\n  +\n    sum(\n      snapmirror_update_successful_count{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n    )\nor on ()\n  vector(0)"
    }
   ]
  },
  {
   "title": "Unprotected Volumes",
   "type": "stat",
   "description": "Number of unprotected volumes.",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n      volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",state!=\"\",svm=~\"$SVM\",type=\"rw\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n    )\n  -\n    count(\n      volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isDestinationOntap=\"true\",isProtected=\"true\",state!=\"\",svm=~\"$SVM\",svm_root=\"false\",type=\"rw\",volume=~\".*$Volume.*\",netapp_cluster=~\"$NetappCluster\"}\n    )\nor\n  vector(0)"
    }
   ]
  },
  {
   "title": "Protected Volumes",
   "type": "stat",
   "description": "Number of protected volumes.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",state!=\"\",svm=~\"$SVM\",type=\"rw\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(\n    volume_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",isDestinationOntap=\"true\",isProtected=\"true\",state!=\"\",svm=~\"$SVM\",svm_root=\"false\",type=\"rw\",volume=~\"$Volume\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
     "legendFormat": "Protected"
    }
   ]
  },
  {
   "title": "Relationships",
   "type": "table",
   "description": "This panel displays detail of all the snapmirror relationships from source side of view.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_duration{relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snapmirror_last_transfer_size{relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snapmirror_lag_time{relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "snapmirror_labels{derived_relationship_type!=\"load_sharing\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Transfer Duration",
   "type": "timeseries",
   "description": "This panel displays duration of the last SnapMirror transfer in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_duration{source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      snapmirror_last_transfer_duration{source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{source_location}} -> {{destination_location}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Lag Time",
   "type": "timeseries",
   "description": "This panel displays amount of time since the last snapmirror transfer in seconds.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snapmirror_lag_time{source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      snapmirror_lag_time{source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{source_location}} -> {{destination_location}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Relationships by Transfer Data",
   "type": "timeseries",
   "description": "This panel displays size in kilobytes (1024 bytes) of the last transfer.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snapmirror_last_transfer_size{source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      snapmirror_last_transfer_size{source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{source_location}} -> {{destination_location}}"
    }
   ]
  },
  {
   "title": "Policy and Lag details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Relationships by Protection Policy",
     "type": "piechart",
     "description": "This panel displays volume relationship count based on the relationship type.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n    snapmirror_labels{derived_relationship_type=\"extended_data_protection\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Asynchronous Mirror"
      },
      {
       "expr": "count(\n    snapmirror_labels{derived_relationship_type=\"mirror_vault\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Asynchronous Mirror and Vault"
      },
      {
       "expr": "count(\n    snapmirror_labels{derived_relationship_type=\"vault\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Asynchronous Vault"
      },
      {
       "expr": "count(\n    snapmirror_labels{derived_relationship_type=\"sync_mirror_strict\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
       "legendFormat": "StrictSync"
      },
      {
       "expr": "count(\n    snapmirror_labels{derived_relationship_type=\"sync_mirror\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Sync"
      },
      {
       "expr": "count(\n    snapmirror_labels{derived_relationship_type=\"automated_failover\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Automated Failover"
      },
      {
       "expr": "count(\n    snapmirror_labels{derived_relationship_type=\"automated_failover_duplex\",relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nor\n  vector(0)",
       "legendFormat": "Automated Failover Duplex"
      }
     ]
    },
    {
     "title": "Relationships by Lag time",
     "type": "piechart",
     "description": "This panel displays volume relationship count based on the lag time bucket.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(\n    (\n          1\n        <\n          snapmirror_lag_time{relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume!=\"\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      <=\n        900\n    )\n  )\nor\n  vector(0)",
       "legendFormat": "<=15 minutes"
      },
      {
       "expr": "count(\n    (\n          900\n        <\n          snapmirror_lag_time{relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume!=\"\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      <=\n        1800\n    )\n  )\nor\n  vector(0)",
       "legendFormat": "16-30 minutes"
      },
      {
       "expr": "count(\n    (\n          1800\n        <\n          snapmirror_lag_time{relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume!=\"\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      <=\n        3600\n    )\n  )\nor\n  vector(0)",
       "legendFormat": "31-60 minutes"
      },
      {
       "expr": "count(\n    (\n        snapmirror_lag_time{relationship_id!=\"\",source_cluster=~\"$Cluster\",source_volume!=\"\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n      >\n        3600\n    )\n  )\nor\n  vector(0)",
       "legendFormat": ">= 60 minutes"
      }
     ]
    },
    {
     "title": "Protection Policy and Lag detail",
     "type": "table",
     "description": "This panel displays snapmirror relationships with protection policy and lag duration details.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "snapmirror_lag_time{source_cluster=~\"$Cluster\",source_volume!=\"\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  * on (source_cluster, source_vserver, source_volume) group_left (derived_relationship_type)\n    snapmirror_labels{source_cluster=~\"$Cluster\",source_volume!=\"\",source_volume=~\".*$Volume.*\",source_vserver=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n>\n  0"
      }
     ]
    }
   ]
  }
 ]
}