{
 "title": "ONTAP: Vscan",
 "tags": [
  "cdot",
  "harvest",
  "ontap"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "SVM",
    "query": {
     "query": "label_values(svm_vscan_scan_latency{system_type!=\"7mode\",datacenter=~\"$Datacenter\", cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, svm)"
    }
   },
   {
    "name": "Scanner",
    "query": {
     "query": "label_values(vscan_scanner_stats_pct_cpu_used{system_type!=\"7mode\",datacenter=~\"$Datacenter\", cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, scanner)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "SVM Vscanner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "description": "Total number of current active connections.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "svm_vscan_connections_active{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "{{svm}}"
    }
   ]
  },
  {
   "title": "Top $TopResources SVMs by Scan Latency",
   "type": "timeseries",
   "description": "Average scan latency.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (cluster, svm) (\n    svm_vscan_scan_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (cluster, svm) (\n      avg_over_time(svm_vscan_scan_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h])\n    )\n  )",
     "legendFormat": "{{svm}}"
    }
   ]
  },
  {
   "title": "Top $TopResources SVM by Dispatch Latency",
   "type": "timeseries",
   "description": "Average dispatch latency.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (cluster, svm) (\n    svm_vscan_dispatch_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (cluster, svm) (\n      avg_over_time(\n        svm_vscan_dispatch_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{svm}}"
    }
   ]
  },
  {
   "title": "Top $TopResources SVMs by Scan Requests Sent to Vscanner Throughput",
   "type": "timeseries",
   "description": "Total number of scan requests sent to the Vscanner per second.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster, svm) (\n    rate(\n      svm_vscan_scan_request_dispatched_rate{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    avg by (cluster, svm) (\n      avg_over_time(\n        svm_vscan_scan_request_dispatched_rate{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{svm}}"
    }
   ]
  },
  {
   "title": "Top $TopResources SVMs by Scan Notifications Received Throughput",
   "type": "timeseries",
   "description": "Total number of scan notifications received by the dispatcher per second.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster, svm) (\n    rate(\n      svm_vscan_scan_noti_received_rate{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    avg by (cluster, svm) (\n      avg_over_time(\n        svm_vscan_scan_noti_received_rate{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{svm}}"
    }
   ]
  },
  {
   "title": "Connection Status Counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Scanners by Scanner Latency",
     "type": "timeseries",
     "description": "Average scan latency.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "avg by (cluster, svm, scanner) (\n    vscan_scan_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scanner=~\"$Scanner\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}\n  )\nand\n  topk(\n    $TopResources,\n    avg by (cluster, svm, scanner) (\n      avg_over_time(\n        vscan_scan_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scanner=~\"$Scanner\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{scanner}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Scanners by Scanner Requests Throughput",
     "type": "timeseries",
     "description": "Total number of scan requests sent to the scanner per second.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (cluster, scanner, svm) (\n    rate(\n      vscan_scan_request_dispatched_rate{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scanner=~\"$Scanner\",netapp_cluster=~\"$NetappCluster\"}[4m]\n    )\n  )\nand\n  topk(\n    $TopResources,\n    avg by (cluster, scanner, svm) (\n      avg_over_time(\n        vscan_scan_request_dispatched_rate{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scanner=~\"$Scanner\",netapp_cluster=~\"$NetappCluster\"}[3h]\n      )\n    )\n  )",
       "legendFormat": "{{scanner}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scanner utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scanner CPU Utilization",
     "type": "timeseries",
     "description": "Percentage CPU utilization on scanner calculated over the last 15 seconds.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vscan_scanner_stats_pct_cpu_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scanner=~\"$Scanner\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{scanner}}"
      }
     ]
    },
    {
     "title": "Scanner Mem Utilization",
     "type": "timeseries",
     "description": "Percentage RAM utilization on scanner calculated over the last 15 seconds.",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vscan_scanner_stats_pct_mem_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scanner=~\"$Scanner\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{scanner}}"
      }
     ]
    },
    {
     "title": "Scanner Network Utilization",
     "type": "timeseries",
     "description": "Percentage network utilization on scanner calculated for the last 15 seconds.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "vscan_scanner_stats_pct_network_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",scanner=~\"$Scanner\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}",
       "legendFormat": "{{scanner}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Vscan Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disconnected Vscan Servers in Cluster",
     "type": "table",
     "description": "Displays disconnected vscan servers.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "vscan_server_disconnected{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",svm=~\"$SVM\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    }
   ]
  }
 ]
}