{
 "title": "ONTAP: Workload",
 "tags": [
  "harvest",
  "ontap",
  "cdot"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "WorkloadClass",
    "label": "Workload Class",
    "query": "user_defined,system_defined,autovolume"
   },
   {
    "name": "Workload",
    "query": {
     "query": "label_values(qos_workload_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\", class=~\"$WorkloadClass\",netapp_cluster=~\"$NetappCluster\"}, workload)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Important Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard requires Workload/QOS counter templates. <br>More information about [ONTAP Performance Guide](https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_9_Performance_-_Resolution_Guide) and [Details in ONTAP Performance KB article](https://kb.netapp.com/on-prem/ontap/Perf/Perf-KBs/What_is_the_difference_in_latency_of_the_same_volume_between_statistics_volume_show_and_qos_statistics_volume_latency_show_commands)."
   }
  },
  { "title": "Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Top $TopResources Workloads by Read IOPS",
   "type": "timeseries",
   "description": "This is the rate of this workload's read operations that completed during the measurement interval.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "qos_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Write IOPS",
   "type": "timeseries",
   "description": "This is the workload's write operations that completed during the measurement interval; measured per second.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "qos_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_write_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Other IOPS",
   "type": "timeseries",
   "description": "This is the workload's other operations that completed during the measurement interval measured per second.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "qos_other_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_other_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Total IOPS",
   "type": "timeseries",
   "description": "Workload operations executed per second.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Read Throughput",
   "type": "timeseries",
   "description": "This is the amount of data read per second from the filer by the workload.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "qos_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Write Throughput",
   "type": "timeseries",
   "description": "This is the amount of data written per second to the filer by the workload.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "qos_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_write_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Average Read Latency",
   "type": "timeseries",
   "description": "This is the average response time for read requests that were initiated by the workload.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "qos_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Average Write Latency",
   "type": "timeseries",
   "description": "This is the average response time for write requests that were initiated by the workload.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "qos_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_write_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Average Latency",
   "type": "timeseries",
   "description": "This is the average response time for requests that were initiated by the workload.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "qos_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_latency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Concurrency",
   "type": "timeseries",
   "description": "This is the average number of concurrent requests for the workload.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "qos_concurrency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_concurrency{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Sequential Reads (%)",
   "type": "timeseries",
   "description": "This is the percentage of reads, performed on behalf of the workload, that were sequential.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "qos_sequential_reads{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_sequential_reads{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Workloads by Sequential Writes (%)",
   "type": "timeseries",
   "description": "This is the percentage of writes, performed on behalf of the workload, that were sequential.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "qos_sequential_writes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_sequential_writes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{workload}}"
    }
   ]
  },
  {
   "title": "Fixed QoS Shared Policy Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Fixed QoS Shared Policy IOPs Utilization (%)",
     "type": "timeseries",
     "description": "This panel represents the proportion of the allocated Input/Output Operations Per Second (IOPs) that is currently being used in a policy, under a fixed Quality of Service (QoS) setting. The percentage is calculated by dividing the current IOPs usage by the total available IOPs, and then multiplying the result by 100.\n\n**Important Note:** This panel only covers policies that are shared across workloads.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(\n    sum by (cluster, datacenter, policy_group) (\n        (\n            qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload!~\".*__[0-9]{4,netapp_cluster=~\"$NetappCluster\"}-.*\"} * 100\n          / on (datacenter, cluster, policy_group) group_left ()\n            label_replace(\n              qos_policy_fixed_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n              \"policy_group\",\n              \"$1\",\n              \"name\",\n              \"(.*)\"\n            )\n        )\n      * on (datacenter, cluster, policy_group) group_left (capacity_shared)\n        label_replace(\n          qos_policy_fixed_labels{capacity_shared=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",max_throughput_iops!=\"\",netapp_cluster=~\"$NetappCluster\"},\n          \"policy_group\",\n          \"$1\",\n          \"name\",\n          \"(.*)\"\n        )\n    ),\n    100\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, policy_group) (\n      (\n          avg_over_time(\n            qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload!~\".*__[0-9]{4,netapp_cluster=~\"$NetappCluster\"}-.*\"}[3h] @ end()\n          )\n        / on (datacenter, cluster, policy_group) group_left ()\n          avg_over_time(\n            (\n                label_replace(\n                  qos_policy_fixed_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n                  \"policy_group\",\n                  \"$1\",\n                  \"name\",\n                  \"(.*)\"\n                )\n              * on (datacenter, cluster, policy_group) group_left (capacity_shared)\n                label_replace(\n                  qos_policy_fixed_labels{capacity_shared=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",max_throughput_iops!=\"\",netapp_cluster=~\"$NetappCluster\"},\n                  \"policy_group\",\n                  \"$1\",\n                  \"name\",\n                  \"(.*)\"\n                )\n            )[3h:] @ end()\n          )\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy_group}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Fixed QoS Shared Policy Bandwidth Utilization (%)",
     "type": "timeseries",
     "description": "This panel represents the proportion of the allocated bandwidth that is currently being used in a policy, under a fixed Quality of Service (QoS) setting. The percentage is calculated by dividing the current bandwidth usage (in MB/s) by the total available bandwidth (also in MB/s), and then multiplying the result by 100.\n\n**Important Note:** This panel specifically covers policies that are shared across workloads.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(\n    sum by (cluster, datacenter, policy_group) (\n        (\n              qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload!~\".*__[0-9]{4,netapp_cluster=~\"$NetappCluster\"}-.*\"} * 100\n            /\n              (1000 * 1000)\n          / on (datacenter, cluster, policy_group) group_left ()\n            label_replace(\n              qos_policy_fixed_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n              \"policy_group\",\n              \"$1\",\n              \"name\",\n              \"(.*)\"\n            )\n        )\n      * on (datacenter, cluster, policy_group) group_left (capacity_shared)\n        label_replace(\n          qos_policy_fixed_labels{capacity_shared=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",max_throughput_mbps!=\"\",netapp_cluster=~\"$NetappCluster\"},\n          \"policy_group\",\n          \"$1\",\n          \"name\",\n          \"(.*)\"\n        )\n    ),\n    100\n  )\nand\n  topk(\n    $TopResources,\n    sum by (cluster, datacenter, policy_group) (\n      (\n          avg_over_time(\n            qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload!~\".*__[0-9]{4,netapp_cluster=~\"$NetappCluster\"}-.*\"}[3h] @ end()\n          )\n        / on (datacenter, cluster, policy_group) group_left ()\n          avg_over_time(\n            (\n                label_replace(\n                  qos_policy_fixed_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n                  \"policy_group\",\n                  \"$1\",\n                  \"name\",\n                  \"(.*)\"\n                )\n              * on (datacenter, cluster, policy_group) group_left (capacity_shared)\n                label_replace(\n                  qos_policy_fixed_labels{capacity_shared=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",max_throughput_mbps!=\"\",netapp_cluster=~\"$NetappCluster\"},\n                  \"policy_group\",\n                  \"$1\",\n                  \"name\",\n                  \"(.*)\"\n                )\n            )[3h:] @ end()\n          )\n      )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy_group}}"
      }
     ]
    },
    {
     "title": "Fixed QoS Shared Policy IOPs Utilization (%)",
     "type": "table",
     "description": "This panel represents the proportion of the allocated Input/Output Operations Per Second (IOPs) that is currently being used in a policy, under a fixed Quality of Service (QoS) setting. The percentage is calculated by dividing the current IOPs usage by the total available IOPs, and then multiplying the result by 100.\n\n**Important Note:** This panel only covers policies that are shared across workloads.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 80 },
     "targets": [
      {
       "expr": "avg_over_time(\n  clamp_max(\n    sum by (cluster, datacenter, policy_group, object_count, max_throughput_iops, max_throughput_mbps, min_throughput_iops, min_throughput_mbps) (\n        (\n            qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload!~\".*__[0-9]{4,netapp_cluster=~\"$NetappCluster\"}-.*\"} * 100\n          / on (datacenter, cluster, policy_group) group_left ()\n            label_replace(\n              qos_policy_fixed_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n              \"policy_group\",\n              \"$1\",\n              \"name\",\n              \"(.*)\"\n            )\n        )\n      * on (datacenter, cluster, policy_group) group_left (capacity_shared, object_count, max_throughput_iops, max_throughput_mbps, min_throughput_iops, min_throughput_mbps)\n        label_replace(\n          qos_policy_fixed_labels{capacity_shared=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",max_throughput_iops!=\"\",netapp_cluster=~\"$NetappCluster\"},\n          \"policy_group\",\n          \"$1\",\n          \"name\",\n          \"(.*)\"\n        )\n    ),\n    100\n  )[3h:]\n)"
      }
     ]
    },
    {
     "title": "Fixed QoS Shared Policy Bandwidth Utilization (%)",
     "type": "table",
     "description": "This panel represents the proportion of the allocated bandwidth that is currently being used in a policy, under a fixed Quality of Service (QoS) setting. The percentage is calculated by dividing the current bandwidth usage (in MB/s) by the total available bandwidth (also in MB/s), and then multiplying the result by 100.\n\n**Important Note:** This panel specifically covers policies that are shared across workloads.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "avg_over_time(\n  clamp_max(\n    sum by (cluster, datacenter, policy_group, object_count, max_throughput_iops, max_throughput_mbps, min_throughput_iops, min_throughput_mbps) (\n        (\n              qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload!~\".*__[0-9]{4,netapp_cluster=~\"$NetappCluster\"}-.*\"} * 100\n            /\n              (1000 * 1000)\n          / on (datacenter, cluster, policy_group) group_left ()\n            label_replace(\n              qos_policy_fixed_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n              \"policy_group\",\n              \"$1\",\n              \"name\",\n              \"(.*)\"\n            )\n        )\n      * on (datacenter, cluster, policy_group) group_left (capacity_shared, object_count, max_throughput_iops, max_throughput_mbps, min_throughput_iops, min_throughput_mbps)\n        label_replace(\n          qos_policy_fixed_labels{capacity_shared=\"true\",cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",max_throughput_mbps!=\"\",netapp_cluster=~\"$NetappCluster\"},\n          \"policy_group\",\n          \"$1\",\n          \"name\",\n          \"(.*)\"\n        )\n    ),\n    100\n  )[3h:]\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Fixed QoS Workload Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Fixed QoS Workload IOPs Utilization (%)",
     "type": "timeseries",
     "description": "This panel represents the proportion of the allocated Input/Output Operations Per Second (IOPs) that is currently being used by Workload, under a fixed Quality of Service (QoS) setting. The percentage is calculated by dividing the current IOPs usage by the total available IOPs, and then multiplying the result by 100.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(\n    (\n        (\n            qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n          / on (datacenter, cluster, policy_group) group_left ()\n            label_replace(\n              qos_policy_fixed_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n              \"policy_group\",\n              \"$1\",\n              \"name\",\n              \"(.*)\"\n            )\n        )\n      *\n        100\n    ),\n    100\n  )\nand\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n        )\n      / on (datacenter, cluster, policy_group) group_left ()\n        avg_over_time(\n          label_replace(\n            qos_policy_fixed_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n            \"policy_group\",\n            \"$1\",\n            \"name\",\n            \"(.*)\"\n          )[3h:] @ end()\n        )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy_group}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Fixed QoS Workload Bandwidth Utilization (%)",
     "type": "timeseries",
     "description": "This panel represents the proportion of the allocated bandwidth that is currently being used by Workload, under a fixed Quality of Service (QoS) setting. The percentage is calculated by dividing the current bandwidth usage (in MB/s) by the total available bandwidth (also in MB/s), and then multiplying the result by 100.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(\n    (\n      (\n          (\n              qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"} * 100\n            /\n              (1000 * 1000)\n          )\n        / on (datacenter, cluster, policy_group) group_left ()\n          label_replace(\n            qos_policy_fixed_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n            \"policy_group\",\n            \"$1\",\n            \"name\",\n            \"(.*)\"\n          )\n      )\n    ),\n    100\n  )\nand\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n        )\n      / on (datacenter, cluster, policy_group) group_left ()\n        avg_over_time(\n          label_replace(\n            qos_policy_fixed_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n            \"policy_group\",\n            \"$1\",\n            \"name\",\n            \"(.*)\"\n          )[3h:] @ end()\n        )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy_group}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Fixed QoS Workload IOPs Utilization (%)",
     "type": "table",
     "description": "This panel represents the proportion of the allocated Input/Output Operations Per Second (IOPs) that is currently being used by Workload, under a fixed Quality of Service (QoS) setting. The percentage is calculated by dividing the current IOPs usage by the total available IOPs, and then multiplying the result by 100.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "avg_over_time(qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h])\n* on (datacenter, cluster, policy_group) group_left (max_throughput_iops, max_throughput_mbps, min_throughput_iops, min_throughput_mbps, capacity_shared)\n  label_replace(\n    qos_policy_fixed_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",max_throughput_iops!=\"\",netapp_cluster=~\"$NetappCluster\"},\n    \"policy_group\",\n    \"$1\",\n    \"name\",\n    \"(.*)\"\n  )"
      }
     ]
    },
    {
     "title": "Fixed QoS Workload Bandwidth Utilization (%)",
     "type": "table",
     "description": "This panel represents the proportion of the allocated bandwidth that is currently being used by Workload, under a fixed Quality of Service (QoS) setting. The percentage is calculated by dividing the current bandwidth usage (in MB/s) by the total available bandwidth (also in MB/s), and then multiplying the result by 100.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 118 },
     "targets": [
      {
       "expr": "avg_over_time(\n    qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h]\n  )\n* on (datacenter, cluster, policy_group) group_left (max_throughput_iops, max_throughput_mbps, min_throughput_iops, min_throughput_mbps, capacity_shared)\n  label_replace(\n    qos_policy_fixed_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",max_throughput_mbps!=\"\",netapp_cluster=~\"$NetappCluster\"},\n    \"policy_group\",\n    \"$1\",\n    \"name\",\n    \"(.*)\"\n  )"
      }
     ]
    }
   ]
  },
  {
   "title": "Adaptive QoS Workload Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Adaptive QoS Workload IOPs Utilization (%)",
     "type": "timeseries",
     "description": "This panel displays the percentage of Input/Output Operations Per Second (IOPs) currently in use relative to the dynamically adjusted IOPs threshold, which is set by an adaptive QoS policy. Unlike fixed QoS settings, adaptive QoS policies allow the IOPs threshold to fluctuate based on predefined criteria and workload demands. The utilization percentage is determined by taking the current IOPs usage, dividing it by the adaptive IOPs threshold at that moment, and then multiplying by 100 to get a percentage.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(\n    (\n        (qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"} * 100)\n      / on (datacenter, cluster, workload, policy_group, volume, lun, svm, qtree, file, wid)\n        qos_workload_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n    ),\n    100\n  )\nand\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n        )\n      / on (datacenter, cluster, workload, policy_group, volume, lun, svm, qtree, file, wid)\n        avg_over_time(\n          qos_workload_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n        )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy_group}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Adaptive QoS Workload Bandwidth Utilization (%)",
     "type": "timeseries",
     "description": "This panel displays the current usage of throughput as a percentage of the adaptive threshold set by an adaptive Quality of Service (QoS) policy. This metric is calculated by dividing the current throughput usage by the adaptive threshold and multiplying by 100. The panel shows data only if the block size is not set to `any`.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "clamp_max(\n    (\n        (\n            (qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"} * 100)\n          /\n            (1000 * 1000)\n        )\n      / on (datacenter, cluster, workload, policy_group, volume, lun, svm, qtree, file, wid)\n        qos_workload_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n    ),\n    100\n  )\nand\n  topk(\n    $TopResources,\n    (\n        avg_over_time(\n          qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n        )\n      / on (datacenter, cluster, workload, policy_group, volume, lun, svm, qtree, file, wid)\n        avg_over_time(\n          qos_workload_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n        )\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{policy_group}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Adaptive QoS Workload IOPs Utilization (%)",
     "type": "table",
     "description": "This panel displays the percentage of Input/Output Operations Per Second (IOPs) currently in use relative to the dynamically adjusted IOPs threshold, which is set by an adaptive QoS policy. Unlike fixed QoS settings, adaptive QoS policies allow the IOPs threshold to fluctuate based on predefined criteria and workload demands. The utilization percentage is determined by taking the current IOPs usage, dividing it by the adaptive IOPs threshold at that moment, and then multiplying by 100 to get a percentage.\n\n`Workload size` would be calculated only when the minimum IOPs exists and it's value is higher than absolute IOPs. \n\nWorkload size = Max IOPs/ Peak IOPs.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "avg_over_time(\n  label_join(\n    clamp_max(\n      (\n          (qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"} * 100)\n        / on (datacenter, cluster, workload, policy_group, volume, lun, svm, qtree, file, wid)\n          qos_workload_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n      ),\n      100\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"cluster\",\n    \"workload\"\n  )[3h:]\n)"
      },
      {
       "expr": "label_join(\n  (\n      qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n    * on (datacenter, cluster, workload, policy_group, volume, lun, svm, qtree, file, wid)\n      (\n          qos_workload_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n        and\n          qos_workload_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n      )\n  ),\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"workload\"\n)"
      },
      {
       "expr": "label_join(\n    qos_workload_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n  and on (cluster, datacenter, workload)\n    qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"workload\"\n)"
      },
      {
       "expr": "label_join(\n    qos_workload_min_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n  and on (cluster, datacenter, workload)\n    qos_ops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"workload\"\n)"
      },
      {
       "expr": "label_join(\n    (\n            1024 * 1024 * 1024 * 1024\n          *\n            qos_workload_max_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n        / on (cluster, datacenter, policy_group, svm) group_left ()\n          label_replace(\n            qos_policy_adaptive_peak_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n            \"policy_group\",\n            \"$1\",\n            \"name\",\n            \"(.*)\"\n          )\n      unless on (cluster, datacenter, policy_group, svm, workload)\n        (\n              qos_workload_min_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n            - on (cluster, datacenter, policy_group, svm) group_left ()\n              label_replace(\n                qos_policy_adaptive_absolute_min_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",netapp_cluster=~\"$NetappCluster\"},\n                \"policy_group\",\n                \"$1\",\n                \"name\",\n                \"(.*)\"\n              )\n          ==\n            0\n        )\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"cluster\",\n    \"workload\"\n  )\nand on (cluster, datacenter, workload)\n  qos_workload_min_throughput_iops{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}"
      }
     ]
    },
    {
     "title": "Adaptive QoS Workload Bandwidth Utilization (%)",
     "type": "table",
     "description": "This panel displays the current usage of throughput as a percentage of the adaptive threshold set by an adaptive Quality of Service (QoS) policy. This metric is calculated by dividing the current throughput usage by the adaptive threshold and multiplying by 100. The panel shows data only if the block size is not set to `any`.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 119 },
     "targets": [
      {
       "expr": "avg_over_time(\n  label_join(\n    clamp_max(\n      (\n          (\n              (qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"} * 100)\n            /\n              (1000 * 1000)\n          )\n        / on (datacenter, cluster, workload, policy_group, volume, lun, svm, qtree, file, wid)\n          qos_workload_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n      ),\n      100\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"cluster\",\n    \"workload\"\n  )[3h:]\n)"
      },
      {
       "expr": "avg_over_time(\n  label_join(\n    (\n        qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n      * on (datacenter, cluster, workload, policy_group, volume, lun, svm, qtree, file, wid)\n        (\n            qos_workload_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n          and\n            qos_workload_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n        )\n    ),\n    \"unique_id\",\n    \"-\",\n    \"datacenter\",\n    \"cluster\",\n    \"workload\"\n  )[3h:]\n)"
      },
      {
       "expr": "label_join(\n    qos_workload_max_throughput_mbps{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",is_adaptive=\"Yes\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\n  and on (cluster, datacenter, workload)\n    qos_total_data{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"},\n  \"unique_id\",\n  \"-\",\n  \"datacenter\",\n  \"cluster\",\n  \"workload\"\n)"
      }
     ]
    }
   ]
  },
  {
   "title": "Read IO Type",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top $TopResources Workloads by Read IO Type bamboo_ssd",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from bamboo_ssd component.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"bamboo_ssd\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"bamboo_ssd\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type cache",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from cache.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"cache\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"cache\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type cloud",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from cloud.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"cloud\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"cloud\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type cloud_s2c",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from cloud_s2c.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"cloud_s2c\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"cloud_s2c\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type disk",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from disk.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"disk\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"disk\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type ext_cache",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from ext_cache.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"ext_cache\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"ext_cache\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type fc_miss",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from fc_miss.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"fc_miss\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"fc_miss\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type hya_cache",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from hya_cache.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"hya_cache\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"hya_cache\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type hya_hdd",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from hya_hdd.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"hya_hdd\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"hya_hdd\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    },
    {
     "title": "Top $TopResources Workloads by Read IO Type hya_non_cache",
     "type": "timeseries",
     "description": "This is the percentage of read requests served from hya_non_cache.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"hya_non_cache\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      qos_read_io_type{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",metric=\"hya_non_cache\",workload=~\"$Workload\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
       "legendFormat": "{{netapp_cluster}} - {{workload}}"
      }
     ]
    }
   ]
  }
 ]
}