{
 "title": "ONTAP: StorageGrid FabricPool",
 "tags": [
  "harvest",
  "ontap",
  "cdot",
  "storagegrid"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "ONTAP Cluster",
    "query": {
     "query": "label_values(aggr_labels{cloud_stores!=\"\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "Aggregate",
    "query": {
     "query": "label_values(aggr_labels{cluster=~\"$Cluster\",cloud_stores!=\"\",netapp_cluster=~\"$NetappCluster\"}, aggr)"
    }
   },
   {
    "name": "SGCluster",
    "label": "SG Cluster",
    "query": {
     "query": "label_values(storagegrid_storage_utilization_data_bytes{netapp_cluster=~\"$NetappCluster\"},cluster)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   },
   {
    "name": "Policy",
    "query": {
     "query": "label_values(storagegrid_private_load_balancer_storage_rx_bytes{cluster=~\"$SGCluster\",netapp_cluster=~\"$NetappCluster\"},policy)"
    }
   },
   {
    "name": "Bucket",
    "label": "Bucket",
    "query": {
     "query": "label_values(cloud_target_labels{cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "ONTAP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Aggregates",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (aggr) (aggr_labels{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}))"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_raid_disk_count{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_volume_count{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Total Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_total{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Available Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aggr_space_available{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Space Used %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(aggr_space_used{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"})\n/\n  sum(aggr_space_total{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"})"
    }
   ]
  },
  {
   "title": "Aggregates",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "aggr_new_status{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "aggr_volume_count{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "aggr_raid_disk_count{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "aggr_space_total{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "aggr_space_used{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "aggr_space_used_percent{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "aggr_labels{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}"
    }
   ]
  },
  {
   "title": "Physical Space Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_physical_used{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Space Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_available{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  {
   "title": "Capacity Tier Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aggr_space_capacity_tier_used{aggr=~\"$Aggregate\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}",
     "legendFormat": "{{node}} - {{aggr}}"
    }
   ]
  },
  { "title": "StorageGrid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Top $TopResources Load Balancer Request Traffic by Policy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8\n*\n  (\n      sum by (cluster, policy) (\n        rate(\n          storagegrid_private_load_balancer_storage_rx_bytes{cluster=~\"$SGCluster\",policy=~\"$Policy\",netapp_cluster=~\"$NetappCluster\"}[4m]\n        )\n      )\n    and on (cluster, policy)\n      topk(\n        $TopResources,\n        sum by (cluster, policy) (\n          avg_over_time(\n            storagegrid_private_load_balancer_storage_rx_bytes{cluster=~\"$SGCluster\",policy=~\"$Policy\",netapp_cluster=~\"$NetappCluster\"}[3h]\n          )\n        )\n      )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{policy}} - Received"
    },
    {
     "expr": "8\n*\n  (\n      sum by (cluster, policy) (\n        rate(\n          storagegrid_private_load_balancer_storage_tx_bytes{cluster=~\"$SGCluster\",policy=~\"$Policy\",netapp_cluster=~\"$NetappCluster\"}[4m]\n        )\n      )\n    and on (cluster, policy)\n      topk(\n        $TopResources,\n        sum by (cluster, policy) (\n          avg_over_time(\n            storagegrid_private_load_balancer_storage_tx_bytes{cluster=~\"$SGCluster\",policy=~\"$Policy\",netapp_cluster=~\"$NetappCluster\"}[3h]\n          )\n        )\n      )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{policy}} - Sent"
    }
   ]
  },
  {
   "title": "Top $TopResources Load Balancer Request Completion Rates by Policy",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (cluster, policy) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{cluster=~\"$SGCluster\",policy=~\"$Policy\",netapp_cluster=~\"$NetappCluster\"}[4m]\n      )\n    )\n  >\n    0\nand on (cluster, policy)\n  topk(\n    $TopResources,\n    sum by (cluster, policy) (\n      avg_over_time(\n        storagegrid_private_load_balancer_storage_request_count{cluster=~\"$SGCluster\",policy=~\"$Policy\",netapp_cluster=~\"$NetappCluster\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{policy}} - Total"
    },
    {
     "expr": "sum by (cluster, policy, method) (\n      rate(\n        storagegrid_private_load_balancer_storage_request_count{cluster=~\"$SGCluster\",policy=~\"$Policy\",netapp_cluster=~\"$NetappCluster\"}[4m]\n      )\n    )\n  >\n    0\nand on (cluster, policy, method)\n  topk(\n    $TopResources,\n    sum by (cluster, policy, method) (\n      avg_over_time(\n        storagegrid_private_load_balancer_storage_request_count{cluster=~\"$SGCluster\",policy=~\"$Policy\",netapp_cluster=~\"$NetappCluster\"}[3h]\n      )\n    )\n  )",
     "legendFormat": "{{netapp_cluster}} - {{policy}} - {{method}}"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "bucket_bytes{bucket=~\"$Bucket\",cluster=~\"$SGCluster\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "bucket_objects{bucket=~\"$Bucket\",cluster=~\"$SGCluster\",netapp_cluster=~\"$NetappCluster\"}"
    }
   ]
  }
 ]
}