{
 "title": "StorageGrid: Tenants",
 "tags": [
  "harvest",
  "storagegrid"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "Datacenter",
    "query": {
     "query": "label_values(tenant_labels{system_type!=\"7mode\"}, datacenter)"
    }
   },
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(tenant_labels{system_type!=\"7mode\",datacenter=~\"$Datacenter\"}, cluster)"
    }
   },
   {
    "name": "NetappCluster",
    "query": {
     "query": "label_values(cluster_new_status{system_type!=\"7mode\",datacenter=~\"$Datacenter\",cluster=~\"$Cluster\"}, netapp_cluster)"
    }
   },
   {
    "name": "Tenant",
    "query": {
     "query": "label_values(tenant_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",netapp_cluster=~\"$NetappCluster\"}, tenant)"
    }
   },
   {
    "name": "Id",
    "query": {
     "query": "label_values(tenant_labels{datacenter=~\"$Datacenter\",cluster=~\"$Cluster\",tenant=~\"$Tenant\",netapp_cluster=~\"$NetappCluster\"}, id)"
    }
   },
   {
    "name": "TopResources",
    "query": "1,2,3,4,5,6,8,10,15,25,50,100,250,500"
   }
  ]
 },
 "panels": [
  { "title": "Tenants and Buckets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top $TopResources Tenants by Capacity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tenant_logical_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",id=~\"$Id\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      tenant_logical_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",id=~\"$Id\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top $TopResources Buckets by Capacity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "bucket_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",tenant=~\"$Tenant\",netapp_cluster=~\"$NetappCluster\"}\nand\n  topk(\n    $TopResources,\n    avg_over_time(\n      bucket_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",tenant=~\"$Tenant\",netapp_cluster=~\"$NetappCluster\"}[3h] @ end()\n    )\n  )",
     "legendFormat": "{{tenant}} - {{bucket}}"
    }
   ]
  },
  {
   "title": "Tenant Quota",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "tenant_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",id=~\"$Id\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "tenant_logical_used{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",id=~\"$Id\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "tenant_logical_quota{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",id=~\"$Id\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "tenant_used_percent{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",id=~\"$Id\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "tenant_objects{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",id=~\"$Id\",netapp_cluster=~\"$NetappCluster\"}"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "table",
   "description": "`Space Used:` The logical size of all objects in the bucket.\n\n`Objects:` The number of objects in the bucket.\n\n`Quota:`  The maximum amount of logical space available for the tenant’s objects. If a quota is not configured, an unlimited amount of space is available.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "bucket_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",tenant=~\"$Tenant\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "bucket_objects{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",tenant=~\"$Tenant\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "bucket_quota_bytes{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",tenant=~\"$Tenant\",netapp_cluster=~\"$NetappCluster\"}"
    },
    {
     "expr": "bucket_labels{cluster=~\"$Cluster\",datacenter=~\"$Datacenter\",tenantID=~\"$ID\",netapp_cluster=~\"$NetappCluster\"}"
    }
   ]
  }
 ]
}